package lasad.shared.communication.objects;

public enum ActionCommands {
	FORCED_LOGOUT, LOGOUT, LEAVE, ERROR, LOGIN, LOGIN_FAILED, HEARTBEATREQUEST, LISTMAP, NO_MAP, NO_USER, EMPTY_MAP, INIT_START, INIT_END, JOIN, USERJOIN, USERLEAVE, USERLIST
}
