package lasad.shared.communication.objects.commands;

public enum Commands{
	AddMapToList("AddMapToList"),
	AddTemplateToList("AddTemplateToList"),
	AddUserToList("AddUserToList"),
	AuthoringFailed("AuthoringFailed"),
	AutoResizeTextBox("AutoResizeTextBox"),
	ChangeFontSize("ChangeFontSize"),
	ConfirmationRequest("ConfirmationRequest"),
	DeleteElement("DeleteElement"),
	DeleteMapFromList("DeleteMapFromList"),
	DeleteOntologyFromList("DeleteOntologyFromList"),
	DeleteTemplateFromList("DeleteTemplateFromList"),
	DeleteUserFromList("DeleteUserFromList"),
	EmptyMap("EmptyMap"), 
	Error("Error"), 
	ErrorInfo("ErrorInfo"),
	FinishAutoOrganize("FinishAutoOrganize"),
	ForcedLogout("ForcedLogout"),
	HeartbeatRequest("HeartbeatRequest"), 
	Info("Info"),
	InitEnd("InitEnd"), 
	InitStart("InitStart"), 
	Join("Join"), 
	Leave("Leave"),
	ListMap("ListMap"), 
	ListOntologies("ListOntologies"), 
	ListUsers("ListUsers"), 
	Login("Login"), 
	LoginFailed("LoginFailed"),
	Logout("Logout"),
	MapDetails("MapDetails"),
	NoMap("NoMap"),
	NoUser("NoUser"), 
	Ontology("Ontology"), 
	OntologyCreated("OntologyCreated"),
	OntologyDetails("OntologyDetails"),
	Ready("Ready"),
	SessionCreated("SessionCreated"),
	StartAutoOrganize("StartAutoOrganize"),
	TemplateCreated("TemplateCreated"),
	TemplateDetails("TemplateDetails"), 
	TemplateListElement("TemplateListElement"),
	UpdateElement("UpdateElement"),
	UserCreated("UserCreated"), 
	UserJoin("UserJoin"),
	UserLeave("UserLeave"), 
	UserList("UserList"), 
	None("None"),
	CreateElement("CreateElement"),
	ImportFinished("ImportFinished"),
	ChatMsg("ChatMsg"), 
	GetTemplates("GetTemplates"),
	CreateTemplate("CreateTemplate"),
	DeleteTemplate("DeleteTemplate"), 
	GetOntologies("GetOntologies"),
	GetOntologyDetails("GetOntologyDetails"),
	CreateOntology("CreateOntology"), 
	DeleteOntology("DeleteOntology"),
	UpdateOntology("UpdateOntology"),
	GetMapsAndTemplates("GetMapsAndTemplates"),
	CreateMap("CreateMap"),
	DeleteMap("DeleteMap"), 
	GetUsers("GetUsers"), 
	CreateUser("CreateUser"),
	DeleteUser("DeleteUser"), 
	Highlight("Highlight"), 
	Request("Request"), 
	List("List"), 
	GetAllOntologiesAndTemplates("GetAllOntologiesAndTemplates"),
	GetOntology("GetOntology"),
	CreateAndJoin("CreateAndJoin"), 
	JoinComplete("JoinComplete"),
	Import("Import"),
    UpdateCursorPosition("UpdateCursorPosition"), 
    Undo("Undo"), 
	NoAction("NoAction"), 
	Start("Start"), 
	SaveLocal("SaveLocal"),
	Heartbeat("Heartbeat"), 
	GetAnswer("GetAnswer"),
	AddAnswer("AddAnswer"),
	Answer("Answer"),
	Load("Load"),
	ListAgentsInfo("ListAgentsInfo"),
	ListAgentsToOntologies("ListAgentsToOntologies"),
	ListAgentsToSessions("ListAgentsToSessions"),
	ListSessionStatus("ListSessionStatus"),
	CompileAgent("CompileAgent"),
	BackgroundImage("BackgroundImage"),
	AddAgentToOntology("AddAgentToOntology"),
	AddAgentToSession("AddAgentToSession"),
	AddOrUpdateAgent("AddOrUpdateAgent"),
	DeleteAgent("DeleteAgent"),
	RemoveAgentFromOntology("RemoveAgentFromOntology"),
	RemoveAgentFromSession("RemoveAgentFromSession"),
	StartSession("StartSession"),
	StopSession("StopSession"),
	AgentMappingsDeleted("AgentMappingsDeleted"),
	ComponentRuntimeStatusChanged("ComponentRuntimeStatusChanged"),
	GetFreshAgentId("GetFreshAgentId"),
	GetFreshPatternId("GetFreshPatternId"),
	SessionRuntimeStatusChanged("SessionRuntimeStatusChanged");
	
	private String oldCommands;

	public String getOldCommands() {
		return oldCommands;
	}
	
	Commands(String oldString){
		oldCommands = oldString;
	}
}

