//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.08.27 at 04:08:09 PM CEST 
//


package lasad.logging.commonformat.util.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "instructions",
    "description"
})
@XmlRootElement(name = "conditions")
public class Conditions {

    @XmlAttribute(name = "creator_application")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String creatorApplication;
    @XmlAttribute(name = "application_version")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String applicationVersion;
    @XmlAttribute(name = "experimenter")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String experimenter;
    protected Instructions instructions;
    protected String description;

    /**
     * Gets the value of the creatorApplication property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCreatorApplication() {
        return creatorApplication;
    }

    /**
     * Sets the value of the creatorApplication property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCreatorApplication(String value) {
        this.creatorApplication = value;
    }

    /**
     * Gets the value of the applicationVersion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getApplicationVersion() {
        return applicationVersion;
    }

    /**
     * Sets the value of the applicationVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setApplicationVersion(String value) {
        this.applicationVersion = value;
    }

    /**
     * Gets the value of the experimenter property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExperimenter() {
        return experimenter;
    }

    /**
     * Sets the value of the experimenter property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExperimenter(String value) {
        this.experimenter = value;
    }

    /**
     * Gets the value of the instructions property.
     * 
     * @return
     *     possible object is
     *     {@link Instructions }
     *     
     */
    public Instructions getInstructions() {
        return instructions;
    }

    /**
     * Sets the value of the instructions property.
     * 
     * @param value
     *     allowed object is
     *     {@link Instructions }
     *     
     */
    public void setInstructions(Instructions value) {
        this.instructions = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

}
