//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.08.27 at 04:08:09 PM CEST 
//


package lasad.logging.commonformat.util.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "pcdata"
})
@XmlRootElement(name = "instruction")
public class Instruction {

    @XmlElement(name = "PCDATA", required = true)
    protected PCDATA pcdata;

    /**
     * Gets the value of the pcdata property.
     * 
     * @return
     *     possible object is
     *     {@link PCDATA }
     *     
     */
    public PCDATA getPCDATA() {
        return pcdata;
    }

    /**
     * Sets the value of the pcdata property.
     * 
     * @param value
     *     allowed object is
     *     {@link PCDATA }
     *     
     */
    public void setPCDATA(PCDATA value) {
        this.pcdata = value;
    }

}
